version: "3.8"
services:
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
  spring-app:
    image: dhananjay12/database-app-using-jib:latest
    ports:
      - "8081:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/employee_app_old?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root
    depends_on:
      mysql:
        condition: service_healthy
  spring-native-app:
    image: dhananjay12/database-app-native-using-buildpacks:0.0.1
    restart: on-failure
    ports:
      - "8082:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/employee_app?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root
    depends_on:
      mysql:
        condition: service_healthy
