version: "3.8"
services:
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_app
      MYSQL_USER: backend
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
  spring-app:
    image: database-app-using-jib:latest
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mariadb://mysql:3306/employee_app?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root
    depends_on:
      mysql:
        condition: service_healthy
